# Generated by Django 6.0.3 on 2026-04-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_course_allow_discussions_course_enrollment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.CharField(blank=True, max_length=280),
        ),
    ]
