# Generated by Django 6.0.3 on 2026-04-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_course_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="ended_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="is_ended",
            field=models.BooleanField(default=False),
        ),
    ]
